### ISSUE TITLE
Plan some regular full day co-working sessions? 

### ISSUE THREAD

**Issue by lwjohnst86** [merely-useful/r-rse#131]
We brought this up at the last meeting. What do you all think of doing a full day co-working session, low expectation, can come and leave whenever, but at least have a day scheduled to work on this? Maybe do it regular (monthly or every 6 weeks) instead of the meetings? Thoughts? Just trying to think of ways we can help each other and move this along more.

**Comment by ian-flores** [comment]
I think this would be a good idea. Did you have dates in mind? 

I think frequency-wise, once-a-month makes sense.

**Comment by k8hertweck** [comment]
This would be super useful for me.

We could also be super lazy about planning this and use our currently scheduled hour every other week for this (or even expand the time window for extra options for times).

In my case, Fridays have more flexibility for me, so if we schedule separately that would work well.

**Comment by k8hertweck** [comment]
Discussed at meeting today with @cwickham and @mbonsma : late July would be good for blocking off some time for coworking, and we also propose cancelling our next meeting, and using the June 30 meeting to plan specifics for the coworking in July.

**Comment by lwjohnst86** [comment]
Discussed in meeting.
