### ISSUE TITLE
Reminder to grep for TODO and FIXME in all content before the end

### ISSUE THREAD

**Issue by joelostblom** [merely-useful/r-rse#58]
Just a reminder issue so that they are not forgotten when we're focusing on other aspects of the book

**Comment by joelostblom** [comment]
There are also some in chapters/14-team-package-dev.Rmd. Maybe you're alrey planning to grep the entire tree for TODOs at the end? Then ill start recordin gthem here

**Comment by lwjohnst86** [comment]
Yea, we'll grep for todos or fixmes.

**Comment by joelostblom** [comment]
Ok changed the title

**Comment by lwjohnst86** [comment]
`grep -r -n -E "TODO|FIXME" *` as a reminder. Could even create a GitHub Action to add a comment here for us :stuck_out_tongue_closed_eyes: (https://github.com/marketplace/actions/create-or-update-comment)
