### ISSUE TITLE
First review phase for content added so far

### ISSUE THREAD

**Issue by lwjohnst86** [merely-useful/r-rse#59]
Please review from start to finish the final exercises and project assignments, as well as the ~syllabus~ (this will be own PR) and index (please review #57).

I've created a branch to review from. Please create a new branch and merge into this branch: [`first-phase-review`](https://github.com/merely-useful/r-rse/tree/first-phase-review)

Tasks:

1. Create your own branch based on [`first-phase-review`](https://github.com/merely-useful/r-rse/tree/first-phase-review)
2. Review from start to finish the content so far. Look for consistency, order, formatting (so it looks good on the website and is consistent across files), and if the final exercises will help with completing the project assignments.
3. Create a merge of the review into the [`first-phase-review`](https://github.com/merely-useful/r-rse/tree/first-phase-review) branch (**NOT** `main`).

Please try to complete this within 1-1.5 months. (Is flexible but would be nice to have it done sooner than later).

**Comment by lwjohnst86** [comment]
Ideas/thoughts: 

- After we finish reviewing and making PR, we schedule a meeting or two just the three of us to discuss and decide on what we've each revised and thought.
- After we finish the above point, maybe every normal meeting we choose two or three chapters and review all together and discuss/agree on what the final exercises look like so far? Might be a bit time consuming overall, but our meetings tend to be pretty short.

We could repeat the process with the other two review stages. It could be a bit time consuming (we could figure out some ways to speed it up), but it would at least get us all on board with what's in the book... and potentially shorten the review stage at the publishers level.

**Comment by k8hertweck** [comment]
I've got some notes about the book as it stands, and have been trying to figure out the best way to communicate those and not cause too many issues with other suggested edits. I think it might be easiest for me to add my comments on top of your existing PR, @lwjohnst86 ? At least then thoughts from the two of us will be consolidated? 

FWIW, most of my comments are about where things are explained in the narrative, not so much about the final exercises. 

I'm happy to meet at a separate time to discuss more; our existing time slot generally works for me (on other days of the week, too!)

**Comment by lwjohnst86** [comment]
Don't worry about causing issues/conflicts, I'll deal with any problems after we finish. In fact, I think it would be better if you did your own completely, so we have something to debate and discuss. But do whatever works or feels best for you!

**Comment by k8hertweck** [comment]
I've done the read through on my own, I'm now trying to figure out how to communicate my thoughts! I'll go through your PR and add comments like "I challenge you to arm wrestle to settle this dispute!"

No, really, since my comments are higher-level, I'll make some notes in your PR that indicate where our opinions differ, and that will hopefully help us scope out subsequent meetings.
