### ISSUE TITLE
Add to contributing: Voice of book, Learner as reader in main content, instructor as reader in instructor sections?

### ISSUE THREAD

**Issue by lwjohnst86** [merely-useful/r-rse#61]
I feel we talked about this already, but just to formalize it here. What is the voice again? I recall saying something like:

- Within chapters/actual course content, reader is learner so use "you" to refer to learner.
- In "Instructions to Instructor"/"how to use this book", reader (hence "you") is assumed to be the instructor

That right?

**Comment by mbonsma** [comment]
I think this was also referenced here: https://github.com/merely-useful/r-rse/pull/27#discussion_r561337552

**Comment by lwjohnst86** [comment]
Thanks  @mbonsma! Ok, we'll do that. I'll add it to the contributing so its "formalized" and recorded.
