### ISSUE TITLE
Create appendix that lists versions of packages and software used

### ISSUE THREAD

**Issue by lwjohnst86** [merely-useful/r-rse#64]
E.g. Git, R, and RStudio versions used. As well as the packages.

**Comment by k8hertweck** [comment]
It would be good to discuss where to reference this appendix in the book: perhaps in the preface chapter, but definitely by the  next chapter (filesystem). Some readers may want to install all software ahead of time, especially if they want to use versions identical to ours (I imagine version numbers won't be present in the actual narrative of the chapters).

Similarly, I think we should specifically mention in the preface that this book is tidyverse-oriented. Right now it's implicit, but we should make it explicit that our selection of tools and packages reflect functions that play nicely together (thereby sidestepping the question of "why don't you use this other package instead?"
