### ISSUE TITLE
Proposal: refer to book instead of course

### ISSUE THREAD

**Issue by k8hertweck** [merely-useful/r-rse#73]
Throughout the chapters, we sometimes refer to this project as a book, and sometimes as a course (for example, these are both used in the preface). I propose we refer specifically to this as a book, as it's a more generic unit that can be translated more easily to a course (than trying to abstract a course to a book).

**Comment by k8hertweck** [comment]
If we wanted to clarify further, we could also refer to "course" in parts that are specific to instructor notes (e.g., about additional homework).

**Comment by lwjohnst86** [comment]
Let's do that! Do you mind putting a mention of this in the CONTRIBUTING doc?
