### ISSUE TITLE
Minutes and agendas

### ISSUE THREAD

**Issue by lwjohnst86** [merely-useful/r-rse#8]
Please only use for minutes and agendas. Each comment should contain both the agenda and the minutes of a single meeting (use edit button to add minutes).

**Comment by lwjohnst86** [comment]
# Meeting 2020-11-

## Agenda

- Discuss and decide on timeline and plan https://github.com/merely-useful/r-rse/issues/1
    - Related: Estimated times when people will work on this (e.g. I will work on this each month for a few full days at a time)
- Discuss and decide on course design https://github.com/merely-useful/r-rse/pull/5/files
- Brainstorm and discuss ideas for item 2 of https://github.com/merely-useful/r-rse/issues/1
    - Discuss and decide how to allocate tasks as this stage
- Plan next meeting and send out calender invites with Zoom link.

**Comment by cwickham** [comment]
# Meeting 2020-12-03
[Thursday, December 3 20:00 UTC](https://www.timeanddate.com/worldclock/fixedtime.html?iso=20201203T12&p1=2213&ah=1)

## Agenda

* Next meeting: Propose [same time, in two weeks](https://www.timeanddate.com/worldclock/fixedtime.html?iso=20201217T12&p1=2213&ah=1)

**Comment by cwickham** [comment]
# Meeting 2020-12-07

[Thursday, December 17 20:00 UTC](https://www.timeanddate.com/worldclock/fixedtime.html?iso=20201217T12&p1=2213&ah=1)

## Agenda

**Comment by cwickham** [comment]
# Meeting 2021-01-14

[Thursday, January 14 20:00 UTC](https://www.timeanddate.com/worldclock/fixedtime.html?iso=20210114T12&p1=2213&ah=1)

## Agenda

## Minutes

**Comment by cwickham** [comment]
# 2021-01-28

[Thursday January 28th 12:00 UTC](https://www.timeanddate.com/worldclock/fixedtime.html?iso=20210128T12&p1=2213&ah=1)

## Agenda

## Minutes

**Comment by cwickham** [comment]
# 2021-02-11

[Thursday Feb 11th 12:00 UTC](https://www.timeanddate.com/worldclock/fixedtime.html?iso=20210211T12&p1=2213&ah=1)

## Agenda

## Minutes

**Comment by cwickham** [comment]
# 2021-02-25

[Thursday Feb 25th 12:00 UTC](https://www.timeanddate.com/worldclock/fixedtime.html?iso=20210225T12&p1=2213&ah=1)

## Agenda

**Comment by cwickham** [comment]
# 2021-03-11

[Thursday Mar 11th 20:00 UTC](https://www.timeanddate.com/worldclock/fixedtime.html?iso=20210311T12&p1=2213&ah=1)

## Agenda

**Comment by cwickham** [comment]
# 2021-03-25

[Thursday March 25th 19:00 UTC](https://www.timeanddate.com/worldclock/fixedtime.html?iso=20210325T12&p1=2213&ah=1)

**Comment by cwickham** [comment]
# 2021-04-08

[Thursday April 8th 19:00 UTC](https://www.timeanddate.com/worldclock/fixedtime.html?iso=20210408T12&p1=2213&ah=1)

**Comment by cwickham** [comment]
# 2021-04-22

[Thursday, April 22, 2021 at 18:00:00](https://www.timeanddate.com/worldclock/fixedtime.html?iso=20210422T11&p1=2213&ah=1)

**Comment by cwickham** [comment]
# 2021-05-06

[Thursday, May 6, 2021 at 18:00:00](https://www.timeanddate.com/worldclock/fixedtime.html?iso=20210506T11&p1=2213&ah=1)

**Comment by cwickham** [comment]
# 2021-05-20

[Thursday, May 20, 2021 at 18:00:00 UTC](https://www.timeanddate.com/worldclock/fixedtime.html?iso=20210520T11&p1=2213&ah=1)

## Agenda

**Comment by lwjohnst86** [comment]
# 2021-05-20

[Thursday, June 3, 2021 at 18:00:00 UTC](https://www.timeanddate.com/worldclock/fixedtime.html?iso=20210603T11&p1=2213&ah=1)

## Agenda

- Progress updates.
- Review and discuss preface and assignment (schedule at #103).

## Minutes

**Comment by cwickham** [comment]
# 2021-06-17

[Thursday, June 17, 2021 at 18:00:00 UTC](https://www.timeanddate.com/worldclock/fixedtime.html?iso=20210617T11&p1=2213&ah=1)

# Agenda

* Progress Updates
* Review
    * [`chapters/02-filesystem.Rmd`](https://github.com/merely-useful/r-rse/blob/main/chapters/02-filesystem.Rmd) led by KH
    * [`chapters/03-package-setup.Rmd`](https://github.com/merely-useful/r-rse/blob/main/chapters/03-package-setup.Rmd) led by CW

**Comment by cwickham** [comment]
# 2021-07-01

[Thursday, July 01, 2021 at 18:00:00 UTC](https://www.timeanddate.com/worldclock/fixedtime.html?iso=20210701T11&p1=2213&ah=1)

**Comment by cwickham** [comment]
# 2021-07-29

[Thursday, July 29, 2021 at 18:00:00 UTC](https://www.timeanddate.com/worldclock/fixedtime.html?iso=20210729T11&p1=2213&ah=1)

**Comment by cwickham** [comment]
# 2021-08-12

[Thursday, Aug 12, 2021 at 18:00:00 UTC](https://www.timeanddate.com/worldclock/fixedtime.html?iso=20210812T11&p1=2213&ah=1)

## Agenda

Review:
* `chapters/09-package-website.Rmd`
* `chapters/11-version-control-workflow.Rmd`

**Comment by k8hertweck** [comment]
# 2021-08-26

[Thursday, Aug 26, 2021 at 18:00:00 UTC](https://www.timeanddate.com/worldclock/fixedtime.html?iso=20210826T11&p1=234&ah=1)

## Agenda

Review:
* `chapters/08-documentation.Rmd`
* `chapters/12-package-release.Rmd`
* Update timeline by 2 months? Check with those not in attendance at previous meeting

## Minutes

**Comment by k8hertweck** [comment]
# 2021-09-23

[Thursday, Sept 23, 2021 at 18:00:00 UTC](https://www.timeanddate.com/worldclock/fixedtime.html?msg=Merely+Useful&iso=20210923T11&p1=234&ah=1)

## Agenda

Review:
* `chapters/12-package-release.Rmd`
* `chapters/13-team-package-dev.Rmd`

Planning for next steps:

**Proposal for updating [timeline](https://github.com/merely-useful/r-rse/issues/1#issue-639616529)**, with deadlines indicated when possible: 
- _by Oct 7_: Ian drafts packaging chapter (for the rest of us to use as template), including both code chunks and narrative (for language/tone)
- _by Oct 7_: Kate identifies which parts of [zipfs package](https://github.com/merely-useful/zipfs) are developed in each chapter
- _at Oct 7 meeting_: finalize final package(s?) and freeze on package code; use [waldo](https://github.com/r-lib/waldo))
- write out code for in-text chunks in chapters, make everything executable (put in R chunk), this doesn't have to be done by person in charge of chapter, guidelines for formatting [here](https://github.com/merely-useful/r-rse/issues/96)
- write sentences comprising the chapter content (noting that some places don't have very clear concepts outlined yet)
- _by mid-December_: write final exercises for each chapter (with possible solutions to ensure feasibility)
- complete review/proofreading of chapters
- write instructions for instructors

**Comment by k8hertweck** [comment]
# 2021-09-23

[Thursday, Sept 23, 2021 at 18:00:00 UTC](https://www.timeanddate.com/worldclock/fixedtime.html?msg=Merely+Useful&iso=20211007T11&p1=234&ah=1)

## Agenda

- review draft of packaging chapter, focusing on use as template for later chapters
- review plan for code/files developed in each chapter
- finalize package code (at least zipfs) and agree on code freeze (and steps needed before then)
- identify at least the next deadline for upcoming tasks (see below)

## Upcoming tasks:
- write out in-text code for chapters, make everything executable (put in R chunk)
- write sentences comprising the chapter content 
- by mid-December: write final exercises for each chapter (with possible solutions to ensure feasibility)
- complete review/proofreading of chapters
- write instructions for instructors

**Comment by lwjohnst86** [comment]
# 2021-11-18

[Thursday, Nov 18, 2021 at 18:00:00 UTC](https://www.timeanddate.com/worldclock/fixedtime.html?msg=Merely+Useful&iso=20211118T11&p1=234&ah=1)

## Agenda

- Updates

**Comment by lwjohnst86** [comment]
# 2021-11-18

## Agenda

- Status updates.
- Did we take minutes from last meeting?

## Minutes

**Comment by lwjohnst86** [comment]
# 2022-01-13

## Agenda

- Status updates.

## Minutes

**Comment by lwjohnst86** [comment]
# 2022-02-24

## Agenda

- Status updates.

## Minutes

**Comment by cwickham** [comment]
# 2022-03-10

## Agenda

- Status updates.
    - CW: Won't make it to meeting, incremental progress on chapter 4.

**Comment by lwjohnst86** [comment]
# 2022-04-07

## Agenda

- Updates

## Minutes

- Maddy finished a rough draft of her chapter
- Others are working along, having difficulty with finding time, but happy with progress.
- Might start stricter/more firmer deadlines during the summer.

**Comment by lwjohnst86** [comment]
# 2022-06-30

## Agenda

- Discuss and plan #131 

## Minutes
