### ISSUE TITLE
Governance for this project

### ISSUE THREAD

**Issue by k8hertweck** [merely-useful/r-rse#87]
As discussed in meeting on 22 April 2021:
- create a governance document for this repository
- move relevant information from contributing document to governance
- reference information about process from [this issue](https://github.com/merely-useful/r-rse/issues/1)
- clarify other necessary information so that we're modeling what we teach

**Comment by k8hertweck** [comment]
Mention from @lwjohnst86 : we need to figure out governance following publication of the book!

**Comment by lwjohnst86** [comment]
Considering you have a fair amount already, do you want me to start this and you can review/add to in a PR?

**Comment by k8hertweck** [comment]
Yes, that would be great, thanks!
