### ISSUE TITLE
Track RStudio shortcuts in separate 'data' file?

### ISSUE THREAD

**Issue by lwjohnst86** [merely-useful/r-rse#95]
Are we going to be teaching RStudio shortcuts? I don't have an opinion, but if we are I think we should keep track of which ones we are showing.

_Originally posted by @ian-flores in https://github.com/merely-useful/r-rse/pull/89#discussion_r624833241_

**Comment by k8hertweck** [comment]
Echoing support from @lwjohnst86 and @mbonsma from the comment linked above.

Luke also suggested tracking them in data file and referencing with inline R code.

I'm not sure what tracking in a data file means; we could include these in an additional appendix more generally about RStudio usage. This way we can include mentions of where menu options to integrate Git can be found, etc.
