### ISSUE TITLE
Tasks to do as content is added (for milestone 7) 

### ISSUE THREAD

**Issue by lwjohnst86** [merely-useful/r-rse#96]
**This is a work-in-progress and something we should discuss.**

There are a few steps to take to ensure we all fit with each other and so that other tasks are easier to do in the end.

## 1. Reformat all current content into a specific format

Before adding any content around the code steps and exercises, first we each need to reformat things into consistent and similar formats. Start by structuring chapters into sections and form the sections:

````
## Section name

### (optional) Sub-section name

- Bullet point summary of text in section

```{r cs-LABEL-NAME}
# Code used in section and shown to learners
```

```{r ce-LABEL-NAME}
# If needed. Code used in section, NOT shown to learners, but needed for auto building of package/book
```

### Exercise: Exercise Name {#ex-EXERCISE-TAG}

1. Summary of steps to do in exercise

```{r es-LABEL-NAME}
# Code for exercise and shown to learner
```

```{r ee-LABEL-NAME}
# If needed. Code for exercise, NOT shown to learner, used for auto building of package/book
```

```{r sol-LABEL-NAME}
# Code for exercise *solution*, NOT shown to learner, (maybe) used for auto building of package/book
```
````

`LABEL-NAME` is for the name of the code chunk:

- `cs-` = "chapter show".
- `ce-` = "chapter execute".
- `es-` = "exercise show".
- `ee-` = "exercise execute".
- `sol-` = "solution".

**Comment by cwickham** [comment]
@lwjohnst86 A few questions that have arisen as I start to implement this:
* I'm following the py-rse convention of adding section labels that start with chapter slug, then section/subsection label, e.g. 
    ```markdown
    # Setting up an R package {#package-setup}
    ## Why create an R package? {#package-setup-why} 
    ```
    Is this OK? 

* In py-rse, exercise sections had labels that started with the chapter slug, followed by `ex-`, e.g.
    ```markdown
    ### Exercise: Explore the structure of a package {#package-setup-ex-structure} 
    ```
    Are we sticking with that too?

* For code chunks, should the chunk label also include the chapter slug or section/exercise label, or can we figure that out programmatically? 
    For instance, the above exercise might have the chunks:

        ```{r es-install, eval = FALSE}
        remotes::install_github("merely-useful/XXX")
        ```

        ```{r es-run}
        library(XXX)
        xxx()
        yyy
        ```
    Should the chunk labels be `es-package-setup-ex-structure-install` and `es-package-setup-ex-structure-run`? Or maybe  `es-structure-install` and `es-structure-run`?

**Comment by mbonsma** [comment]
If I remember our conversation about this correctly, we had decided NOT to include the chapter slug because:
- chapters will probably be built separately and then combined
- if we do decide to build them all at once, can automate adding the slug later
